osx_image: xcode8.2
language: objective-c

podfile: Example/Podfile

before_install:
  - gem install cocoapods -v '1.2.1'

# install:
#   - if [[ ! $(which xcpretty) ]]; then gem install xcpretty --user-install; fi;

script:
  - xcodebuild -workspace Example/ReCaptcha.xcworkspace -scheme ReCaptcha-Example -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.2' build
  - xcodebuild -workspace Example/ReCaptcha.xcworkspace -scheme ReCaptcha-Example -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.2' test
  - pod lib lint --no-clean --quick

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'ReCaptcha'
